@startuml
group human detection
    cerebrum -> sound_system :call dacker
    cerebrum -> image_system :pose detection(catch wavinghand's action)
end

group move to human
    cerebrum -> control_system :go forward
    cerebrum -> control_system : mapping
    image_system -> cerebrum : return distance 
    control_system -> cerebrum : return distance
end

group get order
cerebrum -> sound_system : speak
cerebrum -> sound_system :listen order
sound_system -> cerebrum : order list
end

group return counter
cerebrum -> control_system :move by mapping
end

group close arm
cerebrum ->sound_system : listen
cerebrum ->control_system : close arm
end

group deliver object
cerebrum -> control_system :move by mapping
end

group hand over order
cerebrum -> control_system : hand over
cerebrum -> sound_system : speak order 
end

@enduml
